--4월 11일 화요일 JOIN
SELECT DNAME, ENAME, JOB, SAL FROM EMP, DEPT
WHERE EMP.DEPTNO = DEPT.DEPTNO AND EMP.JOB IN ('MANAGER', 'CLERK')
ORDER BY DNAME;

--alias 사용
SELECT D.DNAME, E.ENAME, E.JOB, E.SAL FROM EMP E INNER JOIN DEPT D
ON E.DEPTNO = D.DEPTNO
WHERE E.DEPTNO IN (10, 20) AND D.DNAME = 'RESEARCH';

--inner join 키워드 사용
SELECT D.DNAME, E.ENAME, E.JOB, E.SAL FROM EMP E INNER JOIN

SELECT * FROM SALGRADE;
SELECT * FROM EMP;

SELECT E.ENAME, E.JOB, E.SAL FROM EMP E, SALGRADE S
WHERE E.SAL BETWEEN S.LOSAL AND S.HISAL AND E.DEPTNO IN (10, 30)
ORDER BY E.ENAME;

--OUTER JOIN
SELECT D.DNAME, E.ENAME, E.JOB, E.SAL FROM EMP E, DEPT D WHERE E.DEPTNO(+) = D.DEPTNO ORDER BY D.DNAME;

--ANSI OUTER JOIN

--equi join
SELECT DNAME, ENAME, JOB, SAL FROM EMP, DEPT
WHERE EMP.DEPTNO = DEPT.DEPTNO AND EMP.JOB IN ('MANAGER', 'CLERK')
ORDER BY DNAME;

SELECT * FROM EMP;
SELECT * FROM DEPT;

