SELECT DNAME, DEPTNO FROM DEPT;
SELECT ENAME, DEPTNO FROM EMP ORDER BY DEPTNO;

SELECT DEPTNO FROM DEPT
UNION
SELECT DEPTNO FROM EMP;

SELECT DEPTNO FROM DEPT
INTERSECT
SELECT DEPTNO FROM EMP;


SELECT E.ENAME||'"S MANAGER IS '||M.ENAME FROM EMP E, EMP M
WHERE E.MGR = M.EMPNO
ORDER BY M.ENAME;



SELECT E.DEPTNO, E.ENAME, E.SAL, 
ROUND((E.SAL / T.TOTAL_SUM) * 100, 2)||'%' AS SAL_RATE
FROM EMP E, (SELECT SUM(SAL) AS TOTAL_SUM FROM EMP) T
ORDER BY E.DEPTNO;




