--0412 JOIN복습
SELECT D.DNAME, E.ENAME, E.JOB, E.SAL FROM EMP E INNER JOIN DEPT D
ON E.DEPTNO = D.DEPTNO;

SELECT DNAME, DEPTNO FROM DEPT;

SELECT ENAME, DEPTNO,  JOB, SAL FROM EMP;

SELECT D.DNAME, E.ENAME, E.JOB, E.SAL 
FROM EMP E INNER JOIN DEPT D
ON E.DEPTNO = D.DEPTNO
WHERE E.DEPTNO IN (10, 20) AND D.DNAME = 'RESEARCH';

--Non Equi JOIN
SELECT E.ENAME, E.JOB, S.GRADE FROM EMP E, SALGRADE S
WHERE E.SAL BETWEEN S.LOSAL AND S.HISAL;

SELECT E.ENAME, E.JOB, E.SAL, S.GRADE FROM EMP E, SALGRADE S
WHERE E.SAL < S.LOSAL AND E.DEPTNO IN (10, 30)
ORDER BY E.ENAME;

--Outer JOIN
--JOIN 조건에 직접 만족되지 않는 정보도 조회
SELECT D.DNAME, E.ENAME, E.JOB, E.SAL FROM EMP E, DEPT D
WHERE E.DEPTNO(+) = D.DEPTNO
ORDER BY D.DNAME;

SELECT D.DNAME, NVL(E.ENAME, '비상근 부서'), E.JOB, E.SAL FROM EMP E, DEPT D
WHERE E.DEPTNO(+) = D.DEPTNO
ORDER BY D.DNAME;

SELECT D.DNAME, E.ENAME, E.JOB, E.SAL FROM EMP E, DEPT D
WHERE E.DEPTNO(+) = D.DEPTNO(+)
ORDER BY D.DNAME;

SELECT * FROM EMP;

SELECT * FROM DEPT;

--Self Join 순환관계
SELECT E.ENAME||'"S MANAGER IS '||M.ENAME
FROM EMP E, EMP M
WHERE E.MGR = M.EMPNO
ORDER BY M.ENAME;

SELECT * FROM EMP;

--카티션곱
SELECT ENAME, JOB, DNAME FROM EMP,DEPT;

SELECT ENAME FROM EMP; --14개행
SELECT DNAME FROM DEPT; --4개행
SELECT ENAME, JOB, DNAME FROM EMP CROSS JOIN DEPT; --56개행

SELECT ENAME, JOB, DNAME FROM EMP, DEPT
WHERE EMP.SAL > 2000 OR DEPT.DEPTNO IN (10, 20);
--SAL > 2000인 행 6개,  뒤에 조건 만족 행 2개

SELECT E.ENAME, E.JOB, E.SAL, S.GRADE FROM EMP E, SALGRADE S
WHERE E.SAL < S.LOSAL AND E.DEPTNO IN (10, 30)
ORDER BY E.ENAME;

SELECT ENAME, SAL, DEPTNO FROM EMP;

SELECT LOSAL FROM SALGRADE;