DROP TABLE SYSTEM;
DROP TABLE RESOURCE_USAGE;

--SYSTEM 테이블 만들기
CREATE TABLE SYSTEM (
SYSTEM_ID		VARCHAR2(5), 
SYSTEM_NAME   	VARCHAR2(20)
);

--행 삽입
INSERT INTO SYSTEM VALUES('XXX', '혜화DB');
INSERT INTO SYSTEM VALUES ('YYY', '강남DB');
INSERT INTO SYSTEM VALUES ('ZZZ', '영등포DB');

--RESOURCE_USAGE 테이블 만들기
CREATE TABLE RESOURCE_USAGE(
SYSTEM_ID 		VARCHAR2(5),
RESOURCE_NAME 	VARCHAR2(10)
);

--행 삽입
INSERT INTO RESOURCE_USAGE VALUES ('XXX', 'FTP');
INSERT INTO RESOURCE_USAGE VALUES ('YYY', 'FTP');
INSERT INTO RESOURCE_USAGE VALUES ('YYY', 'TELNET');
INSERT INTO RESOURCE_USAGE VALUES ('YYY', 'EMAIL');
COMMIT;

SELECT 
    S.SYSTEM_ID, 
    S.SYSTEM_NAME, 
    MAX(CASE WHEN R.RESOURCE_NAME = 'FTP' THEN '사용' ELSE '미사용' END) AS FTP,
    MAX(CASE WHEN R.RESOURCE_NAME = 'TELNET' THEN '사용' ELSE '미사용' END) AS TELNET,
    MAX(CASE WHEN R.RESOURCE_NAME = 'EMAIL' THEN '사용' ELSE '미사용' END) AS EMAIL
FROM 
    SYSTEM S, 
    RESOURCE_USAGE R
WHERE 
    S.SYSTEM_ID = R.SYSTEM_ID(+)
GROUP BY 
    S.SYSTEM_ID, 
    S.SYSTEM_NAME
ORDER BY SYSTEM_ID ASC;