--1번
SELECT D.DNAME, E.ENAME, E.JOB, E.SAL FROM EMP E, DEPT D
WHERE E.DEPTNO(+) = D.DEPTNO
ORDER BY D.DNAME;

SELECT D.DNAME, E.ENAME, E.JOB, E.SAL FROM EMP E, DEPT D
WHERE E.DEPTNO(+)= D.DEPTNO 
AND E.SAL(+) > 2000;
ORDER BY D.DNAME;

SELECT ENAME, DEPTNO, SAL FROM EMP;
SELECT DNAME, DEPTNO FROM DEPT;

--2번
SELECT E.ENAME||'"S MANAGER IS '||NVL(M.ENAME, 'NOBODY')
FROM EMP E, EMP M
WHERE E.MGR = M.EMPNO(+)
ORDER BY M.ENAME;

--EMP E로 가정
SELECT ENAME, MGR, EMPNO, JOB FROM EMP;
--EMP M으로 가정
SELECT ENAME, MGR, EMPNO, JOB FROM EMP;