--1¹ø
SELECT D.DNAME, E.ENAME, E.JOB, E.SAL FROM EMP E, DEPT D
WHERE E.DEPTNO(+) = D.DEPTNO
ORDER BY D.DNAME;

SELECT D.DNAME, E.ENAME, E.JOB, E.SAL FROM EMP E, DEPT D
WHERE E.DEPTNO(+)= D.DEPTNO 
AND E.SAL(+) > 2000;
ORDER BY D.DNAME;

SELECT ENAME, DEPTNO, SAL FROM EMP;
SELECT DNAME, DEPTNO FROM DEPT;