--JOIN 복습




--primary key

DROP TABLE CUSTOMERUNI;

CREATE TABLE CUSTOMERPRI(
ID      VARCHAR2(8)                 CONSTRAINT CUSTOMERPRI_ID_PK PRIMARY KEY,
PWD     VARCHAR2(8)                 NOT NULL,
NAME    VARCHAR2(20),
SEX     CHAR(1)     DEFAULT 'M'     CONSTRAINT CUSTOMERPRI_SEX_CK CHECK(SEX IN ('M', 'F')),
MOBILE  VARCHAR2(14)                CONSTRAINT CUSTOMERPRI_MOBILE_UK UNIQUE,
AGE     NUMBER(3)   DEFAULT 18);

SELECT * FROM CUSTOMERPRI;

INSERT INTO CUSTOMERPRI(ID, PWD, NAME, MOBILE) VALUES('zman', 'ok', '한국', '011');

INSERT INTO CUSTOMERPRI(ID, PWD, NAME) VALUES('xman', 'ok', 'king');

INSERT INTO CUSTOMERPRI(ID, PWD, NAME) VALUES('xman', 'power', 'zzang');

INSERT INTO CUSTOMERPRI(ID, PWD, NAME) VALUES('Xman', 'korea', 'dbzzang');

INSERT INTO CUSTOMERPRI(ID, PWD, NAME) VALUES(lower('xMan'), 'ok', 'zzang');

INSERT INTO CUSTOMERPRI(PWD, NAME) VALUES('ok', 'kim');

UPDATE CUSTOMERPRI SET ID = NULL;
UPDATE CUSTOMERPRI SET ID = 'XMAN';

--FOREIGN KEY

CREATE TABLE 부서 (부서번호   VARCHAR2(2)     CONSTRAINT 부서_부서번호_PK   PRIMARY KEY,
                  부서명     VARCHAR(10)     CONSTRAINT 부서_부서명_NN     NOT NULL
                  );
                  
CREATE TABLE 사원 (사번      VARCHAR2(8)    PRIMARY KEY,
                  이름      VARCHAR2(10),
                  부서번호   VARCHAR2(2),
                  CONSTRAINT 사원_부서_부서번호_FK FOREIGN KEY(부서번호)
                                    REFERENCES 부서(부서번호));
SELECT * FROM 부서;
SELECT * FROM 사원;

DESC 사원
SELECT 
CONSTRAINT_NAME, CONSTRAINT_TYPE, TABLE_NAME,SEARCH_CONDITION,R_CONSTRAINT_NAME,DELETE_RULE,STATUS
FROM USER_CONSTRAINTS
WHERE TABLE_NAME IN ('부서', '사원');

INSERT INTO 사원(사번, 이름, 부서번호) VALUES ('XMAN', 'TUNER', '10');

INSERT INTO 부서(부서번호, 부서명) VALUES('10', '관리');
INSERT INTO 부서(부서번호, 부서명) VALUES('20', '전산');
INSERT INTO 부서(부서번호, 부서명) VALUES('50', '영업');

INSERT INTO 사원(사번, 이름, 부서번호) VALUES('YMAN', 'DBA', '20');

INSERT INTO 사원(사번, 이름, 부서번호) VALUES('ZMAN', 'DEVELOPER', 30);

DELETE FROM 부서 WHERE 부서번호 = 50;

DELETE FROM 부서 WHERE 부서번호 = 10;

SELECT * FROM 사원;

UPDATE 사원 SET 부서번호 = 20 WHERE 부서번호 = 10;
DELETE FROM 부서 WHERE 부서번호 = 10;
                 